In [2]:
import numpy as np

# numpy.random.rand
numpy.random.rand 返回指定维度、元素在[0,1)区间随机的数组  
. 如果不指定形状，则返回一个浮点数

In [15]:
print np.random.rand(4, 3)
print np.random.rand()

[[ 0.31402238  0.99636792  0.23935676]
 [ 0.56081952  0.78428358  0.49387835]
 [ 0.00644813  0.88178774  0.51079476]
 [ 0.17338848  0.64150994  0.67155235]]
0.654303698053


# numpy.random.randint
numpy.random.randint 返回指定范围的整数  
. 不指定形状时返回一个整数，指定形状时返回指定形状的数组

In [14]:
print np.random.randint(0, 10, (3,4))
print np.random.randint(0, 10)

[[8 8 6 3]
 [5 1 5 2]
 [1 6 7 2]]
5


# numpy.random.randn
numpy.random.randn 返回指定形状、标准正态分布的数组  
. 如果不指定形状，则返回一个浮点数

In [13]:
print np.random.randn(4, 2)
print np.random.randn()

[[-0.4601255  -0.82543936]
 [-0.93633169  0.33110578]
 [-2.3773104   0.76073958]
 [-0.20979464  0.31643713]]
0.0987688411604


# 生成随机正态分布数据

In [7]:
#概率分布的标准差，对应于分布的宽度，scale越大越矮胖，scale越小，越瘦高
a = np.random.normal(scale=5,size=20)
a

array([  0.51924214,   3.02535742,   6.35343694,  -7.49563957,
        -2.08746881,   2.57534803,   7.28806415,   5.92075425,
         3.10227849,  -2.4458491 ,   0.93740374,   0.17599775,
        -0.52160957,  -0.65115002,  14.19700234,   3.6316419 ,
         2.85654285,   5.2918698 ,   6.63914884,  -5.56003531])

# reshape维度为-1时，自动推断维度

In [8]:
np.reshape(a, (-1,4))

array([[  0.51924214,   3.02535742,   6.35343694,  -7.49563957],
       [ -2.08746881,   2.57534803,   7.28806415,   5.92075425],
       [  3.10227849,  -2.4458491 ,   0.93740374,   0.17599775],
       [ -0.52160957,  -0.65115002,  14.19700234,   3.6316419 ],
       [  2.85654285,   5.2918698 ,   6.63914884,  -5.56003531]])

# 向上取整保留小数

In [9]:
np.round(a, 2)

array([  0.52,   3.03,   6.35,  -7.5 ,  -2.09,   2.58,   7.29,   5.92,
         3.1 ,  -2.45,   0.94,   0.18,  -0.52,  -0.65,  14.2 ,   3.63,
         2.86,   5.29,   6.64,  -5.56])