In [5]:
import tensorflow as tf
import input_data
mnist = input_data.read_data_sets("../../MNIST_data/", one_hot=True)
x = tf.placeholder("float", [None, 784])
W = tf.Variable(tf.zeros([784,10]))
b = tf.Variable(tf.zeros([10]))
y = tf.nn.softmax(tf.matmul(x,W) + b)
y_ = tf.placeholder("float", [None,10]) 
cross_entropy = -tf.reduce_sum(y_*tf.log(y))
train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cross_entropy)
init = tf.initialize_all_variables()
with tf.Session() as sess:
    sess.run(init)
    for i in range(1000):
      batch_xs, batch_ys = mnist.train.next_batch(100)
      sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})

    correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    print sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels})
    print sess.run(tf.matmul(x,W) + b, feed_dict={x: mnist.test.images})

Extracting ../../MNIST_data/train-images-idx3-ubyte.gz
Extracting ../../MNIST_data/train-labels-idx1-ubyte.gz
Extracting ../../MNIST_data/t10k-images-idx3-ubyte.gz
Extracting ../../MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Use `tf.global_variables_initializer` instead.
0.9117
[[  0.87224448 -10.2214241    0.33182079 ...,  11.89706039   0.13604927
    3.68745637]
 [  5.58471489  -0.80234277  10.31338596 ..., -17.89341354   5.85748863
   -9.57344913]
 [ -6.7474823    6.82624578   2.0124011  ...,   0.66859937   1.0513351
   -0.96859562]
 ..., 
 [ -8.36789703  -7.82768822  -4.27082491 ...,   2.16350126   5.27760029
    6.14078236]
 [ -2.30142307  -1.35720205  -2.8698523  ...,  -5.79357052   6.45761681
   -2.51354861]
 [  4.24283075 -11.04377937   3.78503537 ...,  -8.21087456   0.76977611
   -3.60308051]]


# 准确率  

激活函数|准确率 
--|--
tf.nn.softmax |0.9135
tf.sigmoid |0.6718
tf.tanh |0.098  
tf.nn.relu |0.098  
tf.nn.relu6 |0.098

In [79]:
import sys
sys.path.append("../..")
from DebugTools import *

test_labels = input_data.extract_labels("../../MNIST_data/t10k-labels-idx1-ubyte.gz", one_hot=False)
test_images = input_data.extract_images("../../MNIST_data/t10k-images-idx3-ubyte.gz")

showUserDefinedProperty(mnist.train, True)
print mnist.train.images.shape, mnist.train.labels.shape, mnist.test.labels.shape, mnist.test.labels.shape, labels.shape
print mnist.test.images[0].size
print labels[:10]


Extracting ../../MNIST_data/t10k-labels-idx1-ubyte.gz
Extracting ../../MNIST_data/t10k-images-idx3-ubyte.gz
['_epochs_completed', '_images', '_index_in_epoch', '_labels', '_num_examples', 'epochs_completed', 'images', 'labels', 'next_batch', 'num_examples']
(55000, 784) (55000, 10) (10000, 10) (10000, 10) (10000,)
784
[7 2 1 0 4 1 4 9 5 9]


In [75]:
import numpy
num_labels = labels.shape[0]
num_classes = 10
labels_dense = test_labels
index_offset = numpy.arange(10000) * 10
labels_one_hot = numpy.zeros((num_labels, num_classes))

print labels_one_hot.shape
print labels_one_hot.flat[0]
print labels_dense.ravel()
print labels_dense 

offset = index_offset + labels_dense.ravel()

print "---------------------------"
print offset[0:10]
print offset[10:20]
print "---------------------------"
print labels_one_hot.ravel()[0:10]
print labels_one_hot.ravel()[0:10]

labels_one_hot.flat[index_offset + labels_dense.ravel()] = 1

print "---------------------------"

print labels_one_hot.ravel()[0:10]
print labels_one_hot.ravel()[10:20]

(10000, 10)
0.0
[7 2 1 ..., 4 5 6]
[7 2 1 ..., 4 5 6]
---------------------------
[ 7 12 21 30 44 51 64 79 85 99]
[100 116 129 130 141 155 169 177 183 194]
---------------------------
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
---------------------------
[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]


In [100]:
print test_images.shape
test_images_ = test_images.reshape(10000,28,28)
print test_images_.shape

(10000, 28, 28, 1)
(10000, 28, 28)
